### ISSUE TITLE
Immagini manuale

### ISSUE THREAD

**Issue by esalvucci** [EmiRoAgesci/documentazione_multisite#1]
![https](https://cloud.githubusercontent.com/assets/1481663/7457148/9c389e2e-f28a-11e4-84e2-7c59ff74a3c7.png)

**Comment by esalvucci** [comment]
![login](https://cloud.githubusercontent.com/assets/1481663/7457340/03a4d7a2-f28c-11e4-8f47-08ac941e31c0.png)

**Comment by esalvucci** [comment]
![dashboard](https://cloud.githubusercontent.com/assets/1481663/7549745/2dab95ee-f643-11e4-9b33-2388caa213a2.png)

**Comment by esalvucci** [comment]
![articoli_dashboard](https://cloud.githubusercontent.com/assets/1481663/7457435/ade3280e-f28c-11e4-98ae-80f205b69ca6.png)

**Comment by esalvucci** [comment]
![menu](https://cloud.githubusercontent.com/assets/1481663/7457468/05adc97c-f28d-11e4-8dc6-0fc705d3b8cc.png)

**Comment by yoghi** [comment]
come è possibile? non dovrebbe essere un certificato vero? forse è
http://www.emiroagesci.it/wp-admin/ da usare?

On Mon, May 4, 2015 at 6:21 PM, Enrico Salvucci notifications@github.com
wrote:

> [image: https]
> https://cloud.githubusercontent.com/assets/1481663/7457111/4d9df73c-f28a-11e4-9af5-9db9f768de8d.png
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EmiRoAgesci/documentazione_multisite/issues/1.

## 

Stefano "Yoghi" Tamagnini

**Comment by esalvucci** [comment]
emiroagesci.it/wp-admin si, ma non abbiamo detto che i sottodomini non hanno un loro certificato?
In tal caso effettivamente dovrei correggere l'indirizzo...

**Comment by yoghi** [comment]
Scriverei la differenza, nel senso, quella guida sarà anche per quelli che
in regione usano www.emiroagesci.it

2015-05-05 14:19 GMT+02:00 Enrico Salvucci notifications@github.com:

> emiroagesci.it/wp-admin si, ma non abbiamo detto che i sottodomini non
> hanno un loro certificato?
> In tal caso effettivamente dovrei correggere l'indirizzo...
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/EmiRoAgesci/documentazione_multisite/issues/1#issuecomment-99064239
> .

## 

Stefano "Yoghi" Tamagnini

**Comment by esalvucci** [comment]
Ah ok!

**Comment by esalvucci** [comment]
![https_warning](https://cloud.githubusercontent.com/assets/1481663/7549687/902b9bcc-f640-11e4-8239-99b56bd16fb6.png)
